// <auto-generated />
using System;
using InvoiceParser.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InvoiceParser.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260630101751_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InvoiceParser.Core.Entities.Charge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("t_charge_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("account_number");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<int?>("CarrierId")
                        .HasColumnType("int")
                        .HasColumnName("carrier_id");

                    b.Property<string>("ChargeDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("charge_desc");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("int")
                        .HasColumnName("t_invoice_id");

                    b.Property<string>("Line")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("line");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("location");

                    b.Property<int>("UsocMapId")
                        .HasColumnType("int")
                        .HasColumnName("t_usoc_map_id");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.ToTable("t_charge");
                });

            modelBuilder.Entity("InvoiceParser.Core.Entities.Inventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("t_inventory_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("customer_id");

                    b.Property<string>("EmployeeName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("employee_name");

                    b.Property<string>("InventoryName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("inventory_name");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("int")
                        .HasColumnName("t_invoice_id");

                    b.Property<string>("LocationName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("location_name");

                    b.Property<string>("ReferenceNumber")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("reference_number");

                    b.Property<string>("ServiceType")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("service_type");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.ToTable("t_inventory");
                });

            modelBuilder.Entity("InvoiceParser.Core.Entities.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("t_invoice_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("add_dtm");

                    b.Property<string>("AddUser")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("add_usr");

                    b.Property<decimal?>("BeginningBalance")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("beg_bal");

                    b.Property<string>("CarrierAccount")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("carrier_account");

                    b.Property<string>("CarrierCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("carrier_code");

                    b.Property<int?>("CarrierId")
                        .HasColumnType("int")
                        .HasColumnName("carrier_id");

                    b.Property<string>("CarrierName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("carrier_name");

                    b.Property<decimal?>("CurrentAdjustments")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("curr_adj");

                    b.Property<decimal?>("CurrentCharges")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("curr_chg");

                    b.Property<decimal?>("CurrentTax")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("curr_tax");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("customer_id");

                    b.Property<bool>("EmailSent")
                        .HasColumnType("bit")
                        .HasColumnName("email_sent");

                    b.Property<decimal?>("EndingBalance")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("end_bal");

                    b.Property<DateTime?>("InvoiceDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("invoice_date");

                    b.Property<DateTime?>("InvoiceDueDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("invoice_due_dtm");

                    b.Property<DateTime?>("InvoiceEndDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("invoice_end_dtm");

                    b.Property<string>("InvoiceNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("invoice_number");

                    b.Property<DateTime?>("InvoiceStartDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("invoice_st_dtm");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsSummary")
                        .HasColumnType("bit")
                        .HasColumnName("is_summary");

                    b.Property<decimal?>("Payment")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("payment");

                    b.Property<string>("PdfText")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("pdf_text");

                    b.Property<decimal?>("PreviousAdjustments")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("prev_adj");

                    b.HasKey("Id");

                    b.ToTable("t_invoice");
                });

            modelBuilder.Entity("InvoiceParser.Core.Entities.InvoiceFeedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CarrierId")
                        .HasColumnType("int")
                        .HasColumnName("CarrierId");

                    b.Property<string>("ConfirmedFieldsJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ConfirmedFieldsJson");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("FeedbackText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FeedbackText");

                    b.Property<bool>("IsProcessed")
                        .HasColumnType("bit")
                        .HasColumnName("IsProcessed");

                    b.Property<string>("OriginalChargesJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("OriginalChargesJson");

                    b.Property<string>("OriginalFieldsJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("OriginalFieldsJson");

                    b.Property<string>("PdfText")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PdfText");

                    b.HasKey("Id");

                    b.ToTable("InvoiceFeedback");
                });

            modelBuilder.Entity("InvoiceParser.Core.Entities.LineFeedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CorrectedLabel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("NormalizedText")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("PredictedLabel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RawText")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.ToTable("LineFeedback");
                });

            modelBuilder.Entity("InvoiceParser.Core.Entities.Usage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("t_usage_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AccountId")
                        .HasColumnType("int")
                        .HasColumnName("account_id");

                    b.Property<DateTime>("AddDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("add_dtm");

                    b.Property<int?>("CarrierId")
                        .HasColumnType("int")
                        .HasColumnName("carrier_id");

                    b.Property<string>("Charge")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("charge");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("int")
                        .HasColumnName("t_invoice_id");

                    b.Property<string>("LineNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("line_number");

                    b.Property<string>("UsageAmount")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("usage");

                    b.Property<string>("UsageLimit")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("usage_limit");

                    b.Property<string>("UsageType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("usagetype");

                    b.Property<int?>("UsocMapId")
                        .HasColumnType("int")
                        .HasColumnName("t_usoc_map_id");

                    b.Property<string>("UsocName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("usoc_name");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.ToTable("t_usage");
                });

            modelBuilder.Entity("InvoiceParser.Core.Entities.VendorParsingRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AmountPattern")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("AmountPattern");

                    b.Property<int>("CarrierId")
                        .HasColumnType("int")
                        .HasColumnName("CarrierId");

                    b.Property<string>("ConditionSource")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("ConditionSource");

                    b.Property<string>("ConditionType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("ConditionType");

                    b.Property<int>("DescriptionLineOffset")
                        .HasColumnType("int")
                        .HasColumnName("DescriptionLineOffset");

                    b.Property<int>("FailCount")
                        .HasColumnType("int")
                        .HasColumnName("FailCount");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("FieldName");

                    b.Property<string>("FieldType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("FieldType");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<string>("RegexPattern")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("RegexPattern");

                    b.Property<string>("Section")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Section");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("SortOrder");

                    b.Property<int>("SuccessCount")
                        .HasColumnType("int")
                        .HasColumnName("SuccessCount");

                    b.Property<string>("TargetTable")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TargetTable");

                    b.Property<string>("TransformationsJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TransformationsJson");

                    b.HasKey("Id");

                    b.ToTable("VendorParsingRules");
                });

            modelBuilder.Entity("InvoiceParser.Core.Entities.Charge", b =>
                {
                    b.HasOne("InvoiceParser.Core.Entities.Invoice", "Invoice")
                        .WithMany("Charges")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("InvoiceParser.Core.Entities.Inventory", b =>
                {
                    b.HasOne("InvoiceParser.Core.Entities.Invoice", "Invoice")
                        .WithMany("Inventories")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("InvoiceParser.Core.Entities.Usage", b =>
                {
                    b.HasOne("InvoiceParser.Core.Entities.Invoice", "Invoice")
                        .WithMany("Usages")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("InvoiceParser.Core.Entities.Invoice", b =>
                {
                    b.Navigation("Charges");

                    b.Navigation("Inventories");

                    b.Navigation("Usages");
                });
#pragma warning restore 612, 618
        }
    }
}
