name: 'Opinionated'

on:
  pull_request:
    types:
    - opened
    - synchronize
    - reopened
    - ready_for_review
    - edited
  push:
    branches:
    - master
    - main
    - develop

permissions:
  security-events: write
  packages: read
  actions: read
  contents: read
  id-token: write  # required for cosign image signing

jobs:
  continuous-integration:
    name: 'Continuous Integration'
    uses: AppDirect/actions/.github/workflows/opinionated-ci.yml@master
    secrets: inherit
